version: '3.7'
services:
  redis:
    container_name: redis
    restart: always
    image: 'redis:7'
    ports:
      - "${REDIS_PORT:-6379}:6379"
    env_file:
      - .env
  bot:
    container_name: bot
    restart: always
    build: .
    env_file:
      - .env
    depends_on:
      - redis